version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:14.17.0-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Lint check
          command: yarn lint
  test:
    docker:
      - image: circleci/node:14.17.0-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint check
          command: yarn lint
      - run:
          name: Tests run
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
