export const ADD_STATION_SUCCESS = "ADD_STATION_SUCCESS"
export const DELETE_STATION_SUCCESS = "DELETE_STATION_SUCCESS"
export const FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS"
export const STATION_ERROR = "STATION_ERROR"
