export const FETCH_CURRENT_CITY_DATA_SUCCESS = "FETCH_CURRENT_CITY_DATA_SUCCESS"
export const FETCH_LOCATION_IMAGE_SUCCESS = "FETCH_LOCATION_IMAGE_SUCCESS"
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS"
export const CURRENT_WEATHER_ERROR = "CURRENT_WEATHER_ERROR"
